# Generated by Django 6.0.5 on 2026-06-02 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_prediction', 'Pending ML Prediction'), ('prediction_ready', 'Prediction Ready (Awaiting Doctor)'), ('under_review', 'Under Doctor Review'), ('approved', 'Prescription Approved'), ('rejected', 'Rejected by Doctor'), ('closed', 'Closed')], default='pending_prediction', max_length=30)),
                ('symptoms_raw', models.JSONField(help_text='List of selected symptom strings')),
                ('chief_complaint', models.TextField(blank=True, help_text='Patient-written description in natural language', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=200, null=True)),
                ('prediction_confidence', models.FloatField(blank=True, null=True)),
                ('top_predictions', models.JSONField(blank=True, help_text='[{disease, confidence}] top-3 predictions', null=True)),
                ('ml_raw_response', models.JSONField(blank=True, help_text='Full response from FastAPI service', null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('doctor_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='case_attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('prescription', 'Prescription Scan'), ('lab_result', 'Lab Result'), ('other', 'Other')], default='other', max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='DrugRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=200)),
                ('drug_name', models.CharField(max_length=200)),
                ('egyptian_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g. First-line, Second-line', max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=300, null=True)),
                ('key_side_effects', models.TextField(blank=True, null=True)),
                ('avoid_in', models.TextField(blank=True, null=True)),
                ('allergy_warning', models.TextField(blank=True, null=True)),
                ('drug_interaction_warning', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved by Doctor'), ('rejected', 'Rejected by Doctor')], default='pending', max_length=10)),
                ('doctor_dosage_override', models.CharField(blank=True, help_text='Doctor can override the suggested dosage', max_length=300, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_recommendations', to='cases.case')),
            ],
            options={
                'ordering': ['role', 'drug_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructions', models.TextField(blank=True, help_text='Additional patient instructions', null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_drugs', models.ManyToManyField(blank=True, help_text='Drugs selected and approved by the doctor', to='cases.drugrecommendation')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='cases.case')),
                ('issued_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
